version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - update-types: "version-update:semver-major"
    groups:
      uv:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/helm-frontend/"
    schedule:
      interval: "weekly"
    ignore:
      - update-types: "version-update:semver-major"
    groups:
      npm:
        patterns: ["*"]
