# This GitHub Actions workflow automatically upgrades the pinned versions
# for all Python dependencies (including transitive dependencies)
# every Monday or whenever the workflow is manually triggered.

name: Upgrade requirements

on:
  # schedule:
  #   - cron: "30 15 * * 1"
  workflow_dispatch:

jobs:
  upgrade-requirements:
    name: Upgrade requirements
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.4"
      - name: Upgrade dependencies
        run: uv lock --upgrade
      - name: Install dependencies
        run: uv sync --extra ci
      - name: Write requirements.txt
        run: uv pip freeze --exclude-editable > requirements.txt
        # Need to manually run tests here because the pull request opened later will not
        # run the test workflow.
        #
        # From https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
        #
        #     ...events triggered by the GITHUB_TOKEN... will not create a new workflow run.
        #     This prevents you from accidentally creating recursive workflow runs. For example,
        #     if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow
        #     will not run even when the repository contains a workflow configured to run when
        #     push events occur.
      - name: Run linter
        run: ./pre-commit.sh
      - name: Run tests
        run: uv run pytest
      - name: Run helm-run
        run: uv run helm-run --suite test --run-entries simple1:model=simple/model1 --max-eval-instances 10 --exit-on-error
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Upgrade requirements
          title: "Upgrade requirements"
          branch: actions/upgrade-requirements
          delete-branch: true
          body: Auto-generated from GitHub Actions.
